name: Build
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install
    - name: Test with tox
      run: tox run -e ${{ matrix.python-version }}
